trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'  # Specify the Node.js version
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'Install dependencies and build Angular project'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'drop'
      displayName: 'Publish build artifacts'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '61b532f2-d4bc-49e0-9643-ee037058aacb'
        appName: 'pruebas-seguridad-front'
        package: '$(System.ArtifactsDirectory)/drop'
