# Este pipeline se ejecuta cuando se hace un push a la rama principal
trigger:
- main

# Define la imagen de la máquina virtual que se utilizará
pool:
  vmImage: 'ubuntu-latest'  # Aquí se usa Ubuntu; asegúrate de que esto es lo que necesitas

# Define las etapas y pasos
steps:
# Instalar la versión necesaria de Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Actualiza a la versión de Node.js que usas para Angular
  displayName: 'Instalar Node.js'

# Instalar Angular CLI y las dependencias, y construir la aplicación
- script: |
    npm install -g @angular/cli  # Instala Angular CLI globalmente
    npm install  # Instala dependencias del proyecto
    ng build --prod  # Compila el proyecto Angular para producción
  displayName: 'Instalar Angular CLI, dependencias, y construir la aplicación'

# Desplegar el resultado en Azure App Service
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(61b532f2-d4bc-49e0-9643-ee037058aacb)'  # Tu conexión de Azure
    appType: 'webApp'  # Tipo de aplicación: webApp para Windows
    WebAppName: 'pruebas-seguridad-front'  # Nombre de tu App Service
    package: '$(System.DefaultWorkingDirectory)/dist/<nombre-de-tu-aplicación>'  # Ruta a los archivos construidos
  displayName: 'Desplegar a Azure App Service'
