trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    displayName: 'Install Node.js'

- script: |
    npm install
    npm run build -- --prod
  displayName: 'Install and build Angular app'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '61b532f2-d4bc-49e0-9643-ee037058aacb'
    appType: 'webAppWindows'  # Aquí se especifica el tipo de aplicación
    WebAppName: 'pruebas-seguridad-front'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist'
    enableCustomDeployment: true
  displayName: 'Deploy to Azure App Service'
